@echo off
cd /d "%~dp0electron-agent\app"
echo [1/4] Installing dependencies...
call npm install --production
echo [2/4] Obfuscating main.cjs...
npx javascript-obfuscator main.cjs --output main.cjs --compact true --control-flow-flattening true --dead-code-injection true --string-array true --string-array-encoding rc4 --self-defending true --disable-console-output false
echo [3/4] Packing asar...
npx asar pack . ..\dist\app-v3.11.0.asar
echo [4/4] Calculating hash...
certutil -hashfile ..\dist\app-v3.11.0.asar SHA256
echo DONE - Upload app-v3.11.0.asar to platform
pause
