// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Identificar usu\xE1rio autenticado",
  description: "Retorna o e-mail e o ID do usu\xE1rio autenticado via OAuth no servidor MCP. \xDAtil para verificar a conex\xE3o.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const payload = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail?.() ?? null,
      client_id: ctx.getClientId?.() ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-farms.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  if (!url || !anon) throw new Error("Supabase env vars are not configured");
  return createClient(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated. Sign in and try again." }],
    isError: true
  };
}

// src/lib/mcp/tools/list-farms.ts
var list_farms_default = defineTool2({
  name: "list_farms",
  title: "Listar fazendas do usu\xE1rio",
  description: "Retorna todas as fazendas \xE0s quais o usu\xE1rio autenticado tem acesso (id, nome e status).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("farms").select("id, name, created_at").order("name", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { farms: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-equipments.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_equipments_default = defineTool3({
  name: "list_equipments",
  title: "Listar equipamentos de uma fazenda",
  description: "Retorna bombas/po\xE7os/reservat\xF3rios cadastrados na fazenda informada, com estado atual e hor\xE1rio da \xFAltima atualiza\xE7\xE3o.",
  inputSchema: {
    farm_id: z2.string().uuid().describe("UUID da fazenda (use list_farms para obter).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ farm_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("equipments").select("id, name, type, hw_id, status, last_outputs_state, updated_at").eq("farm_id", farm_id).order("name", { ascending: true }).limit(200);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { equipments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-notifications.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_notifications_default = defineTool4({
  name: "list_recent_notifications",
  title: "Listar notifica\xE7\xF5es/alarmes recentes",
  description: "Retorna as notifica\xE7\xF5es/alertas mais recentes de uma fazenda (padr\xE3o: \xFAltimas 20).",
  inputSchema: {
    farm_id: z3.string().uuid().describe("UUID da fazenda."),
    limit: z3.number().int().min(1).max(100).describe("Quantas notifica\xE7\xF5es retornar (1\u2013100).").default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ farm_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("farm_notifications").select("id, title, message, severity, created_at, equipment_id").eq("farm_id", farm_id).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { notifications: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "dnyukgfedredvxpzjpqz";
var mcp_default = defineMcp({
  name: "renov-gestor-bombas-mcp",
  title: "RENOV Gestor de Bombas",
  version: "0.1.0",
  instructions: "Ferramentas de leitura do RENOV Gestor de Bombas: listar fazendas do usu\xE1rio, equipamentos por fazenda e notifica\xE7\xF5es/alarmes recentes. Todas as chamadas respeitam RLS e agem como o usu\xE1rio autenticado. Use `whoami` para confirmar a conex\xE3o.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_farms_default, list_equipments_default, list_notifications_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
